DEFAULT_IMAGE_PATH = '%s/media/search/default_framework_logo.png'

QUERY_TYPE_CHOICE_BY_NAME = 'by_name'
QUERY_TYPE_CHOICE_BY_NUMBER = 'by_number'
QUERY_TYPE_CHOICE_BY_VALUE = 'by_value'
QUERY_TYPE_CHOICE_SEARCH_ALL = 'search_all'

QUERY_TYPE_CHOICES = (
    (QUERY_TYPE_CHOICE_BY_NAME, QUERY_TYPE_CHOICE_BY_NAME),
    (QUERY_TYPE_CHOICE_BY_NUMBER, QUERY_TYPE_CHOICE_BY_NUMBER),
    (QUERY_TYPE_CHOICE_BY_VALUE, QUERY_TYPE_CHOICE_BY_VALUE),
    (QUERY_TYPE_CHOICE_SEARCH_ALL, QUERY_TYPE_CHOICE_SEARCH_ALL),
)

DEFAULT_RESULTS_PER_PAGE = 10
DEFAULT_SUGGESTIONS_NUMBER = 10

INQUIRY_EMAIL_SENT = "Sent email regarding inquiry"
PREFERENCE_DELETED = "Preference deleted successfully"
PREFERENCE_CREATED = "Preference created successfully"
INVALID_FRAMEWORK_SEARCH = "Invalid data"

EMPTY_QUERY_EXCEPTION_MSG = "The query returned zero results"

INVALID_CPV_CODE = "cpv_code is not valid"
